/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateSessionInput {
  'gameName' : string,
  'maxParticipants' : bigint,
}
export type Error = { 'sessionFull' : null } |
  { 'alreadyExists' : null } |
  { 'invalidInput' : string } |
  { 'notFound' : null } |
  { 'unauthorized' : null } |
  { 'sessionNotFound' : null };
export type GradeLevel = { 'basic1' : null } |
  { 'basic2' : null } |
  { 'basic3' : null } |
  { 'basic4' : null } |
  { 'basic5' : null } |
  { 'basic6' : null } |
  { 'basic7' : null } |
  { 'basic8' : null } |
  { 'basic9' : null };
export interface HubProgress {
  'totalMissions' : bigint,
  'hubId' : string,
  'lastUpdated' : bigint,
  'unlocked' : boolean,
  'completionPercent' : bigint,
  'missionsCompleted' : bigint,
}
export interface HubProgressUpdate {
  'totalMissions' : bigint,
  'hubId' : string,
  'unlocked' : boolean,
  'missionsCompleted' : bigint,
}
export interface LeaderboardEntry {
  'username' : string,
  'rank' : bigint,
  'achievedAt' : Timestamp,
  'score' : bigint,
  'playerPrincipal' : Principal,
  'accuracy' : bigint,
}
export interface PersonalBest {
  'timeSpent' : bigint,
  'achievedAt' : Timestamp,
  'gameId' : string,
  'score' : bigint,
  'accuracy' : bigint,
}
export interface ProgressUpdate {
  'playTimeSeconds' : bigint,
  'dateString' : string,
  'coinsEarned' : bigint,
  'xpEarned' : bigint,
}
export interface ProgressionView {
  'xp' : bigint,
  'lastPlayedDate' : string,
  'unlockedAchievements' : Array<string>,
  'coins' : bigint,
  'totalPlayTime' : bigint,
  'currentLevel' : bigint,
  'dailyStreak' : bigint,
}
export interface RegisterInput {
  'username' : string,
  'role' : UserRole,
  'gradeLevel' : [] | [GradeLevel],
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type Result_1 = { 'ok' : HubProgress } |
  { 'err' : Error };
export type Result_2 = { 'ok' : UserProfileView } |
  { 'err' : Error };
export type Result_3 = { 'ok' : SessionView } |
  { 'err' : Error };
export type Result_4 = { 'ok' : ProgressionView } |
  { 'err' : Error };
export interface ScoreInput {
  'timeSpent' : bigint,
  'gameId' : string,
  'score' : bigint,
  'accuracy' : bigint,
}
export interface ScoreRecord {
  'completedAt' : Timestamp,
  'timeSpent' : bigint,
  'gameId' : string,
  'score' : bigint,
  'accuracy' : bigint,
}
export type SessionStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'waiting' : null };
export interface SessionView {
  'status' : SessionStatus,
  'participants' : Array<Principal>,
  'createdAt' : Timestamp,
  'hostPrincipal' : Principal,
  'gameName' : string,
  'gameState' : string,
  'sessionId' : string,
  'maxParticipants' : bigint,
}
export interface SubjectSummary {
  'completedHubs' : bigint,
  'overallPercent' : bigint,
  'totalHubs' : bigint,
  'subjectId' : string,
}
export type Timestamp = bigint;
export interface UpdateGameStateInput {
  'status' : SessionStatus,
  'gameState' : string,
  'sessionId' : string,
}
export interface UserProfile {
  'username' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'gradeLevel' : [] | [GradeLevel],
}
export interface UserProfileView {
  'username' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'gradeLevel' : [] | [GradeLevel],
}
export type UserRole = { 'admin' : null } |
  { 'teacher' : null } |
  { 'student' : null } |
  { 'parent' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'applyProgressUpdate' : ActorMethod<[ProgressUpdate], Result_4>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createSession' : ActorMethod<[CreateSessionInput], Result_3>,
  'getAllHubProgress' : ActorMethod<[], Array<HubProgress>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getHubProgress' : ActorMethod<[string], [] | [HubProgress]>,
  'getMyPersonalBest' : ActorMethod<[string], [] | [PersonalBest]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getMyProgression' : ActorMethod<[], [] | [ProgressionView]>,
  'getMyRecentScores' : ActorMethod<[], Array<ScoreRecord>>,
  'getSession' : ActorMethod<[string], [] | [SessionView]>,
  'getSubjectSummary' : ActorMethod<[string], SubjectSummary>,
  'getTopScores' : ActorMethod<[string], Array<LeaderboardEntry>>,
  'getUserProfile' : ActorMethod<[Principal], Result_2>,
  'getUserProgression' : ActorMethod<[Principal], Result_4>,
  'getWeeklyScores' : ActorMethod<[string, string], Array<LeaderboardEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinSession' : ActorMethod<[string], Result_3>,
  'leaveSession' : ActorMethod<[string], Result>,
  'listWaitingSessions' : ActorMethod<[string], Array<SessionView>>,
  'recordScore' : ActorMethod<[ScoreInput], Result>,
  'registerProfile' : ActorMethod<[RegisterInput], Result_2>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unlockAchievement' : ActorMethod<[string], Result>,
  'updateGameState' : ActorMethod<[UpdateGameStateInput], Result>,
  'updateHubProgress' : ActorMethod<[HubProgressUpdate], Result_1>,
  'updateUsername' : ActorMethod<[string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];