/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProgressUpdate = IDL.Record({
  'playTimeSeconds' : IDL.Nat,
  'dateString' : IDL.Text,
  'coinsEarned' : IDL.Nat,
  'xpEarned' : IDL.Nat,
});
export const ProgressionView = IDL.Record({
  'xp' : IDL.Nat,
  'lastPlayedDate' : IDL.Text,
  'unlockedAchievements' : IDL.Vec(IDL.Text),
  'coins' : IDL.Nat,
  'totalPlayTime' : IDL.Nat,
  'currentLevel' : IDL.Nat,
  'dailyStreak' : IDL.Nat,
});
export const Error = IDL.Variant({
  'sessionFull' : IDL.Null,
  'alreadyExists' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
  'sessionNotFound' : IDL.Null,
});
export const Result_4 = IDL.Variant({ 'ok' : ProgressionView, 'err' : Error });
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateSessionInput = IDL.Record({
  'gameName' : IDL.Text,
  'maxParticipants' : IDL.Nat,
});
export const SessionStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'waiting' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const SessionView = IDL.Record({
  'status' : SessionStatus,
  'participants' : IDL.Vec(IDL.Principal),
  'createdAt' : Timestamp,
  'hostPrincipal' : IDL.Principal,
  'gameName' : IDL.Text,
  'gameState' : IDL.Text,
  'sessionId' : IDL.Text,
  'maxParticipants' : IDL.Nat,
});
export const Result_3 = IDL.Variant({ 'ok' : SessionView, 'err' : Error });
export const HubProgress = IDL.Record({
  'totalMissions' : IDL.Nat,
  'hubId' : IDL.Text,
  'lastUpdated' : IDL.Int,
  'unlocked' : IDL.Bool,
  'completionPercent' : IDL.Nat,
  'missionsCompleted' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'student' : IDL.Null,
  'parent' : IDL.Null,
});
export const GradeLevel = IDL.Variant({
  'basic1' : IDL.Null,
  'basic2' : IDL.Null,
  'basic3' : IDL.Null,
  'basic4' : IDL.Null,
  'basic5' : IDL.Null,
  'basic6' : IDL.Null,
  'basic7' : IDL.Null,
  'basic8' : IDL.Null,
  'basic9' : IDL.Null,
});
export const UserProfileView = IDL.Record({
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'gradeLevel' : IDL.Opt(GradeLevel),
});
export const PersonalBest = IDL.Record({
  'timeSpent' : IDL.Nat,
  'achievedAt' : Timestamp,
  'gameId' : IDL.Text,
  'score' : IDL.Nat,
  'accuracy' : IDL.Nat,
});
export const ScoreRecord = IDL.Record({
  'completedAt' : Timestamp,
  'timeSpent' : IDL.Nat,
  'gameId' : IDL.Text,
  'score' : IDL.Nat,
  'accuracy' : IDL.Nat,
});
export const SubjectSummary = IDL.Record({
  'completedHubs' : IDL.Nat,
  'overallPercent' : IDL.Nat,
  'totalHubs' : IDL.Nat,
  'subjectId' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'username' : IDL.Text,
  'rank' : IDL.Nat,
  'achievedAt' : Timestamp,
  'score' : IDL.Nat,
  'playerPrincipal' : IDL.Principal,
  'accuracy' : IDL.Nat,
});
export const Result_2 = IDL.Variant({ 'ok' : UserProfileView, 'err' : Error });
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ScoreInput = IDL.Record({
  'timeSpent' : IDL.Nat,
  'gameId' : IDL.Text,
  'score' : IDL.Nat,
  'accuracy' : IDL.Nat,
});
export const RegisterInput = IDL.Record({
  'username' : IDL.Text,
  'role' : UserRole,
  'gradeLevel' : IDL.Opt(GradeLevel),
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'gradeLevel' : IDL.Opt(GradeLevel),
});
export const UpdateGameStateInput = IDL.Record({
  'status' : SessionStatus,
  'gameState' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const HubProgressUpdate = IDL.Record({
  'totalMissions' : IDL.Nat,
  'hubId' : IDL.Text,
  'unlocked' : IDL.Bool,
  'missionsCompleted' : IDL.Nat,
});
export const Result_1 = IDL.Variant({ 'ok' : HubProgress, 'err' : Error });

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'applyProgressUpdate' : IDL.Func([ProgressUpdate], [Result_4], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createSession' : IDL.Func([CreateSessionInput], [Result_3], []),
  'getAllHubProgress' : IDL.Func([], [IDL.Vec(HubProgress)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getHubProgress' : IDL.Func([IDL.Text], [IDL.Opt(HubProgress)], ['query']),
  'getMyPersonalBest' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PersonalBest)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getMyProgression' : IDL.Func([], [IDL.Opt(ProgressionView)], ['query']),
  'getMyRecentScores' : IDL.Func([], [IDL.Vec(ScoreRecord)], ['query']),
  'getSession' : IDL.Func([IDL.Text], [IDL.Opt(SessionView)], ['query']),
  'getSubjectSummary' : IDL.Func([IDL.Text], [SubjectSummary], ['query']),
  'getTopScores' : IDL.Func([IDL.Text], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [Result_2], ['query']),
  'getUserProgression' : IDL.Func([IDL.Principal], [Result_4], ['query']),
  'getWeeklyScores' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinSession' : IDL.Func([IDL.Text], [Result_3], []),
  'leaveSession' : IDL.Func([IDL.Text], [Result], []),
  'listWaitingSessions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SessionView)],
      ['query'],
    ),
  'recordScore' : IDL.Func([ScoreInput], [Result], []),
  'registerProfile' : IDL.Func([RegisterInput], [Result_2], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unlockAchievement' : IDL.Func([IDL.Text], [Result], []),
  'updateGameState' : IDL.Func([UpdateGameStateInput], [Result], []),
  'updateHubProgress' : IDL.Func([HubProgressUpdate], [Result_1], []),
  'updateUsername' : IDL.Func([IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProgressUpdate = IDL.Record({
    'playTimeSeconds' : IDL.Nat,
    'dateString' : IDL.Text,
    'coinsEarned' : IDL.Nat,
    'xpEarned' : IDL.Nat,
  });
  const ProgressionView = IDL.Record({
    'xp' : IDL.Nat,
    'lastPlayedDate' : IDL.Text,
    'unlockedAchievements' : IDL.Vec(IDL.Text),
    'coins' : IDL.Nat,
    'totalPlayTime' : IDL.Nat,
    'currentLevel' : IDL.Nat,
    'dailyStreak' : IDL.Nat,
  });
  const Error = IDL.Variant({
    'sessionFull' : IDL.Null,
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
    'sessionNotFound' : IDL.Null,
  });
  const Result_4 = IDL.Variant({ 'ok' : ProgressionView, 'err' : Error });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateSessionInput = IDL.Record({
    'gameName' : IDL.Text,
    'maxParticipants' : IDL.Nat,
  });
  const SessionStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'waiting' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const SessionView = IDL.Record({
    'status' : SessionStatus,
    'participants' : IDL.Vec(IDL.Principal),
    'createdAt' : Timestamp,
    'hostPrincipal' : IDL.Principal,
    'gameName' : IDL.Text,
    'gameState' : IDL.Text,
    'sessionId' : IDL.Text,
    'maxParticipants' : IDL.Nat,
  });
  const Result_3 = IDL.Variant({ 'ok' : SessionView, 'err' : Error });
  const HubProgress = IDL.Record({
    'totalMissions' : IDL.Nat,
    'hubId' : IDL.Text,
    'lastUpdated' : IDL.Int,
    'unlocked' : IDL.Bool,
    'completionPercent' : IDL.Nat,
    'missionsCompleted' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'student' : IDL.Null,
    'parent' : IDL.Null,
  });
  const GradeLevel = IDL.Variant({
    'basic1' : IDL.Null,
    'basic2' : IDL.Null,
    'basic3' : IDL.Null,
    'basic4' : IDL.Null,
    'basic5' : IDL.Null,
    'basic6' : IDL.Null,
    'basic7' : IDL.Null,
    'basic8' : IDL.Null,
    'basic9' : IDL.Null,
  });
  const UserProfileView = IDL.Record({
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'gradeLevel' : IDL.Opt(GradeLevel),
  });
  const PersonalBest = IDL.Record({
    'timeSpent' : IDL.Nat,
    'achievedAt' : Timestamp,
    'gameId' : IDL.Text,
    'score' : IDL.Nat,
    'accuracy' : IDL.Nat,
  });
  const ScoreRecord = IDL.Record({
    'completedAt' : Timestamp,
    'timeSpent' : IDL.Nat,
    'gameId' : IDL.Text,
    'score' : IDL.Nat,
    'accuracy' : IDL.Nat,
  });
  const SubjectSummary = IDL.Record({
    'completedHubs' : IDL.Nat,
    'overallPercent' : IDL.Nat,
    'totalHubs' : IDL.Nat,
    'subjectId' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'username' : IDL.Text,
    'rank' : IDL.Nat,
    'achievedAt' : Timestamp,
    'score' : IDL.Nat,
    'playerPrincipal' : IDL.Principal,
    'accuracy' : IDL.Nat,
  });
  const Result_2 = IDL.Variant({ 'ok' : UserProfileView, 'err' : Error });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ScoreInput = IDL.Record({
    'timeSpent' : IDL.Nat,
    'gameId' : IDL.Text,
    'score' : IDL.Nat,
    'accuracy' : IDL.Nat,
  });
  const RegisterInput = IDL.Record({
    'username' : IDL.Text,
    'role' : UserRole,
    'gradeLevel' : IDL.Opt(GradeLevel),
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'gradeLevel' : IDL.Opt(GradeLevel),
  });
  const UpdateGameStateInput = IDL.Record({
    'status' : SessionStatus,
    'gameState' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const HubProgressUpdate = IDL.Record({
    'totalMissions' : IDL.Nat,
    'hubId' : IDL.Text,
    'unlocked' : IDL.Bool,
    'missionsCompleted' : IDL.Nat,
  });
  const Result_1 = IDL.Variant({ 'ok' : HubProgress, 'err' : Error });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'applyProgressUpdate' : IDL.Func([ProgressUpdate], [Result_4], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createSession' : IDL.Func([CreateSessionInput], [Result_3], []),
    'getAllHubProgress' : IDL.Func([], [IDL.Vec(HubProgress)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getHubProgress' : IDL.Func([IDL.Text], [IDL.Opt(HubProgress)], ['query']),
    'getMyPersonalBest' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PersonalBest)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
    'getMyProgression' : IDL.Func([], [IDL.Opt(ProgressionView)], ['query']),
    'getMyRecentScores' : IDL.Func([], [IDL.Vec(ScoreRecord)], ['query']),
    'getSession' : IDL.Func([IDL.Text], [IDL.Opt(SessionView)], ['query']),
    'getSubjectSummary' : IDL.Func([IDL.Text], [SubjectSummary], ['query']),
    'getTopScores' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [Result_2], ['query']),
    'getUserProgression' : IDL.Func([IDL.Principal], [Result_4], ['query']),
    'getWeeklyScores' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinSession' : IDL.Func([IDL.Text], [Result_3], []),
    'leaveSession' : IDL.Func([IDL.Text], [Result], []),
    'listWaitingSessions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SessionView)],
        ['query'],
      ),
    'recordScore' : IDL.Func([ScoreInput], [Result], []),
    'registerProfile' : IDL.Func([RegisterInput], [Result_2], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unlockAchievement' : IDL.Func([IDL.Text], [Result], []),
    'updateGameState' : IDL.Func([UpdateGameStateInput], [Result], []),
    'updateHubProgress' : IDL.Func([HubProgressUpdate], [Result_1], []),
    'updateUsername' : IDL.Func([IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };