/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    username: string;
    rank: bigint;
    achievedAt: Timestamp;
    score: bigint;
    playerPrincipal: Principal;
    accuracy: bigint;
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: UserProfileView;
} | {
    __kind__: "err";
    err: Error_;
};
export interface UpdateGameStateInput {
    status: SessionStatus;
    gameState: string;
    sessionId: string;
}
export interface ProgressUpdate {
    playTimeSeconds: bigint;
    dateString: string;
    coinsEarned: bigint;
    xpEarned: bigint;
}
export interface PersonalBest {
    timeSpent: bigint;
    achievedAt: Timestamp;
    gameId: string;
    score: bigint;
    accuracy: bigint;
}
export interface HubProgress {
    totalMissions: bigint;
    hubId: string;
    lastUpdated: bigint;
    unlocked: boolean;
    completionPercent: bigint;
    missionsCompleted: bigint;
}
export type Error_ = {
    __kind__: "sessionFull";
    sessionFull: null;
} | {
    __kind__: "alreadyExists";
    alreadyExists: null;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} | {
    __kind__: "sessionNotFound";
    sessionNotFound: null;
};
export interface ScoreInput {
    timeSpent: bigint;
    gameId: string;
    score: bigint;
    accuracy: bigint;
}
export type Result_1 = {
    __kind__: "ok";
    ok: HubProgress;
} | {
    __kind__: "err";
    err: Error_;
};
export interface ProgressionView {
    xp: bigint;
    lastPlayedDate: string;
    unlockedAchievements: Array<string>;
    coins: bigint;
    totalPlayTime: bigint;
    currentLevel: bigint;
    dailyStreak: bigint;
}
export type Result_4 = {
    __kind__: "ok";
    ok: ProgressionView;
} | {
    __kind__: "err";
    err: Error_;
};
export interface ScoreRecord {
    completedAt: Timestamp;
    timeSpent: bigint;
    gameId: string;
    score: bigint;
    accuracy: bigint;
}
export interface HubProgressUpdate {
    totalMissions: bigint;
    hubId: string;
    unlocked: boolean;
    missionsCompleted: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Result_3 = {
    __kind__: "ok";
    ok: SessionView;
} | {
    __kind__: "err";
    err: Error_;
};
export interface CreateSessionInput {
    gameName: string;
    maxParticipants: bigint;
}
export interface UserProfileView {
    username: string;
    createdAt: Timestamp;
    role: UserRole;
    gradeLevel?: GradeLevel;
}
export interface SubjectSummary {
    completedHubs: bigint;
    overallPercent: bigint;
    totalHubs: bigint;
    subjectId: string;
}
export interface RegisterInput {
    username: string;
    role: UserRole;
    gradeLevel?: GradeLevel;
}
export interface SessionView {
    status: SessionStatus;
    participants: Array<Principal>;
    createdAt: Timestamp;
    hostPrincipal: Principal;
    gameName: string;
    gameState: string;
    sessionId: string;
    maxParticipants: bigint;
}
export interface UserProfile {
    username: string;
    createdAt: Timestamp;
    role: UserRole;
    gradeLevel?: GradeLevel;
}
export enum GradeLevel {
    basic1 = "basic1",
    basic2 = "basic2",
    basic3 = "basic3",
    basic4 = "basic4",
    basic5 = "basic5",
    basic6 = "basic6",
    basic7 = "basic7",
    basic8 = "basic8",
    basic9 = "basic9"
}
export enum SessionStatus {
    active = "active",
    completed = "completed",
    waiting = "waiting"
}
export enum UserRole {
    admin = "admin",
    teacher = "teacher",
    student = "student",
    parent = "parent"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    applyProgressUpdate(update: ProgressUpdate): Promise<Result_4>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    createSession(input: CreateSessionInput): Promise<Result_3>;
    getAllHubProgress(): Promise<Array<HubProgress>>;
    getCallerUserProfile(): Promise<UserProfileView | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getHubProgress(hubId: string): Promise<HubProgress | null>;
    getMyPersonalBest(gameId: string): Promise<PersonalBest | null>;
    getMyProfile(): Promise<UserProfileView | null>;
    getMyProgression(): Promise<ProgressionView | null>;
    getMyRecentScores(): Promise<Array<ScoreRecord>>;
    getSession(sessionId: string): Promise<SessionView | null>;
    getSubjectSummary(subjectId: string): Promise<SubjectSummary>;
    getTopScores(gameId: string): Promise<Array<LeaderboardEntry>>;
    getUserProfile(principal: Principal): Promise<Result_2>;
    getUserProgression(principal: Principal): Promise<Result_4>;
    getWeeklyScores(gameId: string, weekKey: string): Promise<Array<LeaderboardEntry>>;
    isCallerAdmin(): Promise<boolean>;
    joinSession(sessionId: string): Promise<Result_3>;
    leaveSession(sessionId: string): Promise<Result>;
    listWaitingSessions(gameName: string): Promise<Array<SessionView>>;
    recordScore(input: ScoreInput): Promise<Result>;
    registerProfile(input: RegisterInput): Promise<Result_2>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unlockAchievement(achievementId: string): Promise<Result>;
    updateGameState(input: UpdateGameStateInput): Promise<Result>;
    updateHubProgress(update: HubProgressUpdate): Promise<Result_1>;
    updateUsername(newUsername: string): Promise<Result>;
}
import type { Error as _Error, GradeLevel as _GradeLevel, HubProgress as _HubProgress, PersonalBest as _PersonalBest, ProgressionView as _ProgressionView, RegisterInput as _RegisterInput, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, SessionStatus as _SessionStatus, SessionView as _SessionView, Timestamp as _Timestamp, UpdateGameStateInput as _UpdateGameStateInput, UserProfile as _UserProfile, UserProfileView as _UserProfileView, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async applyProgressUpdate(arg0: ProgressUpdate): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.applyProgressUpdate(arg0);
                return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyProgressUpdate(arg0);
            return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createSession(arg0: CreateSessionInput): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0);
                return from_candid_Result_3_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0);
            return from_candid_Result_3_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHubProgress(): Promise<Array<HubProgress>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHubProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHubProgress();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHubProgress(arg0: string): Promise<HubProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHubProgress(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHubProgress(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPersonalBest(arg0: string): Promise<PersonalBest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPersonalBest(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPersonalBest(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProgression(): Promise<ProgressionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProgression();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProgression();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRecentScores(): Promise<Array<ScoreRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRecentScores();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRecentScores();
            return result;
        }
    }
    async getSession(arg0: string): Promise<SessionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubjectSummary(arg0: string): Promise<SubjectSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubjectSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubjectSummary(arg0);
            return result;
        }
    }
    async getTopScores(arg0: string): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopScores(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopScores(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_Result_2_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_Result_2_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProgression(arg0: Principal): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProgression(arg0);
                return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProgression(arg0);
            return from_candid_Result_4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyScores(arg0: string, arg1: string): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyScores(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyScores(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinSession(arg0: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.joinSession(arg0);
                return from_candid_Result_3_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinSession(arg0);
            return from_candid_Result_3_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async leaveSession(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveSession(arg0);
                return from_candid_Result_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveSession(arg0);
            return from_candid_Result_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listWaitingSessions(arg0: string): Promise<Array<SessionView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWaitingSessions(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWaitingSessions(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordScore(arg0: ScoreInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.recordScore(arg0);
                return from_candid_Result_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordScore(arg0);
            return from_candid_Result_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerProfile(arg0: RegisterInput): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProfile(to_candid_RegisterInput_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_2_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProfile(to_candid_RegisterInput_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_2_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async unlockAchievement(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockAchievement(arg0);
                return from_candid_Result_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockAchievement(arg0);
            return from_candid_Result_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGameState(arg0: UpdateGameStateInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGameState(to_candid_UpdateGameStateInput_n40(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGameState(to_candid_UpdateGameStateInput_n40(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateHubProgress(arg0: HubProgressUpdate): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHubProgress(arg0);
                return from_candid_Result_1_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHubProgress(arg0);
            return from_candid_Result_1_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUsername(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUsername(arg0);
                return from_candid_Result_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUsername(arg0);
            return from_candid_Result_n29(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_GradeLevel_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GradeLevel): GradeLevel {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SessionView_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionView): SessionView {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfileView_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileView): UserProfileView {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): UserProfileView | null {
    return value.length === 0 ? null : from_candid_UserProfileView_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GradeLevel]): GradeLevel | null {
    return value.length === 0 ? null : from_candid_GradeLevel_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HubProgress]): HubProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PersonalBest]): PersonalBest | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProgressionView]): ProgressionView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionView]): SessionView | null {
    return value.length === 0 ? null : from_candid_SessionView_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SessionStatus;
    participants: Array<Principal>;
    createdAt: _Timestamp;
    hostPrincipal: Principal;
    gameName: string;
    gameState: string;
    sessionId: string;
    maxParticipants: bigint;
}): {
    status: SessionStatus;
    participants: Array<Principal>;
    createdAt: Timestamp;
    hostPrincipal: Principal;
    gameName: string;
    gameState: string;
    sessionId: string;
    maxParticipants: bigint;
} {
    return {
        status: from_candid_SessionStatus_n11(_uploadFile, _downloadFile, value.status),
        participants: value.participants,
        createdAt: value.createdAt,
        hostPrincipal: value.hostPrincipal,
        gameName: value.gameName,
        gameState: value.gameState,
        sessionId: value.sessionId,
        maxParticipants: value.maxParticipants
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    createdAt: _Timestamp;
    role: _UserRole;
    gradeLevel: [] | [_GradeLevel];
}): {
    username: string;
    createdAt: Timestamp;
    role: UserRole;
    gradeLevel?: GradeLevel;
} {
    return {
        username: value.username,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n16(_uploadFile, _downloadFile, value.role),
        gradeLevel: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.gradeLevel))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
} | {
    waiting: null;
}): SessionStatus {
    return "active" in value ? SessionStatus.active : "completed" in value ? SessionStatus.completed : "waiting" in value ? SessionStatus.waiting : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    teacher: null;
} | {
    student: null;
} | {
    parent: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "teacher" in value ? UserRole.teacher : "student" in value ? UserRole.student : "parent" in value ? UserRole.parent : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ProgressionView;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: ProgressionView;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    basic1: null;
} | {
    basic2: null;
} | {
    basic3: null;
} | {
    basic4: null;
} | {
    basic5: null;
} | {
    basic6: null;
} | {
    basic7: null;
} | {
    basic8: null;
} | {
    basic9: null;
}): GradeLevel {
    return "basic1" in value ? GradeLevel.basic1 : "basic2" in value ? GradeLevel.basic2 : "basic3" in value ? GradeLevel.basic3 : "basic4" in value ? GradeLevel.basic4 : "basic5" in value ? GradeLevel.basic5 : "basic6" in value ? GradeLevel.basic6 : "basic7" in value ? GradeLevel.basic7 : "basic8" in value ? GradeLevel.basic8 : "basic9" in value ? GradeLevel.basic9 : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfileView;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: UserProfileView;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfileView_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sessionFull: null;
} | {
    alreadyExists: null;
} | {
    invalidInput: string;
} | {
    notFound: null;
} | {
    unauthorized: null;
} | {
    sessionNotFound: null;
}): {
    __kind__: "sessionFull";
    sessionFull: null;
} | {
    __kind__: "alreadyExists";
    alreadyExists: null;
} | {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} | {
    __kind__: "sessionNotFound";
    sessionNotFound: null;
} {
    return "sessionFull" in value ? {
        __kind__: "sessionFull",
        sessionFull: value.sessionFull
    } : "alreadyExists" in value ? {
        __kind__: "alreadyExists",
        alreadyExists: value.alreadyExists
    } : "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : "sessionNotFound" in value ? {
        __kind__: "sessionNotFound",
        sessionNotFound: value.sessionNotFound
    } : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _HubProgress;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: HubProgress;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SessionView;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: SessionView;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_SessionView_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SessionView>): Array<SessionView> {
    return value.map((x)=>from_candid_SessionView_n9(_uploadFile, _downloadFile, x));
}
function to_candid_GradeLevel_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GradeLevel): _GradeLevel {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterInput_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterInput): _RegisterInput {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_SessionStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionStatus): _SessionStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateGameStateInput_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateGameStateInput): _UpdateGameStateInput {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    role: UserRole;
    gradeLevel?: GradeLevel;
}): {
    username: string;
    role: _UserRole;
    gradeLevel: [] | [_GradeLevel];
} {
    return {
        username: value.username,
        role: to_candid_UserRole_n34(_uploadFile, _downloadFile, value.role),
        gradeLevel: value.gradeLevel ? candid_some(to_candid_GradeLevel_n36(_uploadFile, _downloadFile, value.gradeLevel)) : candid_none()
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    createdAt: Timestamp;
    role: UserRole;
    gradeLevel?: GradeLevel;
}): {
    username: string;
    createdAt: _Timestamp;
    role: _UserRole;
    gradeLevel: [] | [_GradeLevel];
} {
    return {
        username: value.username,
        createdAt: value.createdAt,
        role: to_candid_UserRole_n34(_uploadFile, _downloadFile, value.role),
        gradeLevel: value.gradeLevel ? candid_some(to_candid_GradeLevel_n36(_uploadFile, _downloadFile, value.gradeLevel)) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: SessionStatus;
    gameState: string;
    sessionId: string;
}): {
    status: _SessionStatus;
    gameState: string;
    sessionId: string;
} {
    return {
        status: to_candid_SessionStatus_n42(_uploadFile, _downloadFile, value.status),
        gameState: value.gameState,
        sessionId: value.sessionId
    };
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    teacher: null;
} | {
    student: null;
} | {
    parent: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.teacher ? {
        teacher: null
    } : value == UserRole.student ? {
        student: null
    } : value == UserRole.parent ? {
        parent: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GradeLevel): {
    basic1: null;
} | {
    basic2: null;
} | {
    basic3: null;
} | {
    basic4: null;
} | {
    basic5: null;
} | {
    basic6: null;
} | {
    basic7: null;
} | {
    basic8: null;
} | {
    basic9: null;
} {
    return value == GradeLevel.basic1 ? {
        basic1: null
    } : value == GradeLevel.basic2 ? {
        basic2: null
    } : value == GradeLevel.basic3 ? {
        basic3: null
    } : value == GradeLevel.basic4 ? {
        basic4: null
    } : value == GradeLevel.basic5 ? {
        basic5: null
    } : value == GradeLevel.basic6 ? {
        basic6: null
    } : value == GradeLevel.basic7 ? {
        basic7: null
    } : value == GradeLevel.basic8 ? {
        basic8: null
    } : value == GradeLevel.basic9 ? {
        basic9: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionStatus): {
    active: null;
} | {
    completed: null;
} | {
    waiting: null;
} {
    return value == SessionStatus.active ? {
        active: null
    } : value == SessionStatus.completed ? {
        completed: null
    } : value == SessionStatus.waiting ? {
        waiting: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
